# Generated by Django 4.1.6 on 2023-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stat_third_block',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
